name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run test
    runs-on: ${{ matrix.macos }}

    strategy:
      fail-fast: false
      matrix:
        macos: [macos-26, macos-15]
        xcode: ["Xcode_16.4.app", "Xcode_26.3.app"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log available xcode versions
        run: |
          ls /Applications/ | grep "Xcode"

      - name: Select xcode version
        run: |
          sudo xcode-select -s /Applications/$XCODE_VERSION
        env:
          XCODE_VERSION: ${{ matrix.xcode }}

      - name: Log xcodebuild version
        run: |
          xcodebuild -version

      - name: Run tests
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}

        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild test -scheme "TestAppUITests" -project "TestApp.xcodeproj" -destination "platform=$platform,name=$device"
